## Import Dependencies

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
# Loading the dataset : 
df = pd.read_csv('Cars_price.csv')
df

   cylinders   milage   year    price
0          3    30000   2024  2500000
1          4    25000   2022  3100000
2          4    50000   2020  2400000
3          6    30000   2023  5000000
4          8    25000   2022  8000000

In [5]:
df.columns

Index(['cylinders', ' milage', ' year', ' price'], dtype='object')

In [12]:
# Preprocessing : 
df.columns = df.columns.str.strip()
print(df.columns)

Index(['cylinders', 'milage', 'year', 'price'], dtype='object')

In [41]:
# Lets add a row : 
df.loc[5] = [3,50000,None,2100000]

In [42]:
df

   cylinders   milage    year      price
0        3.0  30000.0  2024.0  2500000.0
1        4.0  25000.0  2022.0  3100000.0
2        4.0  50000.0  2020.0  2400000.0
3        6.0  30000.0  2023.0  5000000.0
4        8.0  25000.0  2022.0  8000000.0
5        3.0  50000.0     NaN  2100000.0

In [43]:
df.describe()

       cylinders        milage        year         price
count   6.000000      6.000000     5.00000  6.000000e+00
mean    4.666667  35000.000000  2022.20000  3.850000e+06
std     1.966384  11832.159566     1.48324  2.284513e+06
min     3.000000  25000.000000  2020.00000  2.100000e+06
25%     3.250000  26250.000000  2022.00000  2.425000e+06
50%     4.000000  30000.000000  2022.00000  2.800000e+06
75%     5.500000  45000.000000  2023.00000  4.525000e+06
max     8.000000  50000.000000  2024.00000  8.000000e+06

In [52]:
mean_year = int(df['year'].mean())
df['year'] = df['year'].fillna(float(mean_year))

In [53]:
df

   cylinders   milage    year      price
0        3.0  30000.0  2024.0  2500000.0
1        4.0  25000.0  2022.0  3100000.0
2        4.0  50000.0  2020.0  2400000.0
3        6.0  30000.0  2023.0  5000000.0
4        8.0  25000.0  2022.0  8000000.0
5        3.0  50000.0  2022.0  2100000.0

In [54]:
# Training the model : 
reg = linear_model.LinearRegression()
reg.fit(df[['cylinders', 'milage', 'year']], df.price)

LinearRegression()

In [55]:
reg.coef_

array([ 1.12790004e+06, -5.56135770e+00,  2.09623275e+05])

In [58]:
reg.intercept_

np.float64(-425112085.04289496)

In [63]:
reg.predict([[4,30000,2021]])

C:\Users\hi\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([2881312.94293165])

## Working with hiring dataset :

In [65]:
df = pd.read_csv('hiring.csv')
df

   experience  test_score  interview_score  salary
0         NaN         8.0                9   50000
1         NaN         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         NaN                7   72000
7        11.0         7.0                8   80000

In [67]:
df['experience'].fillna(0, inplace=True)

C:\Users\hi\AppData\Local\Temp\ipykernel_4184\3844921659.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['experience'].fillna(0, inplace=True)

In [68]:
df

   experience  test_score  interview_score  salary
0         0.0         8.0                9   50000
1         0.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         NaN                7   72000
7        11.0         7.0                8   80000

In [79]:
import math

mean_test = df['test_score'].mean()
df['test_score'] = df.test_score.fillna(math.floor(mean_test))
df

   experience  test_score  interview_score  salary
0         0.0         8.0                9   50000
1         0.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         7.0                7   72000
7        11.0         7.0                8   80000

In [80]:
reg_hiring = linear_model.LinearRegression()
reg.fit(df[['experience', 'test_score','interview_score']], df.salary)

LinearRegression()

In [82]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [83]:
reg.intercept_

np.float64(14992.651446693133)

In [87]:
reg.predict([[2, 9, 6],[12, 10, 10]])

C:\Users\hi\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([53713.86677124, 93747.79628651])

In [89]:
import pickle

with open('car_pred_model','wb') as file : 
    pickle.dump(reg, file)

In [91]:
with open('car_pred_model', 'rb') as file : 
    mp = pickle.load(file)

mp.predict([[2,9,6]])

C:\Users\hi\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([53713.86677124])

# Using car prices dataset :

In [107]:
cars = pd.read_csv('carprices.csv')
cars

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [108]:
cars.columns = ['Car_Model', 'Milage', 'Sell_Price', 'Age']
cars

                Car_Model  Milage  Sell_Price  Age
0                  BMW X5   69000       18000    6
1                  BMW X5   35000       34000    3
2                  BMW X5   57000       26100    5
3                  BMW X5   22500       40000    2
4                  BMW X5   46000       31500    4
5                 Audi A5   59000       29400    5
6                 Audi A5   52000       32000    5
7                 Audi A5   72000       19300    6
8                 Audi A5   91000       12000    8
9   Mercedez Benz C class   67000       22000    6
10  Mercedez Benz C class   83000       20000    7
11  Mercedez Benz C class   79000       21000    7
12  Mercedez Benz C class   59000       33000    5

In [109]:
dummies = pd.get_dummies(cars.Car_Model)
dummies

    Audi A5  BMW X5  Mercedez Benz C class
0     False    True                  False
1     False    True                  False
2     False    True                  False
3     False    True                  False
4     False    True                  False
5      True   False                  False
6      True   False                  False
7      True   False                  False
8      True   False                  False
9     False   False                   True
10    False   False                   True
11    False   False                   True
12    False   False                   True

In [131]:
dum_cars = pd.concat([cars,dummies],axis='columns')
dum_cars

,Car_Model,Milage,Sell_Price,Age,Audi A5,BMW X5,Mercedez Benz C class
0,BMW X5,69000,18000,6,False,True,False
1,BMW X5,35000,34000,3,False,True,False
2,BMW X5,57000,26100,5,False,True,False
3,BMW X5,22500,40000,2,False,True,False
4,BMW X5,46000,31500,4,False,True,False
5,Audi A5,59000,29400,5,True,False,False
6,Audi A5,52000,32000,5,True,False,False
7,Audi A5,72000,19300,6,True,False,False
8,Audi A5,91000,12000,8,True,False,False
9,Mercedez Benz C class,67000,22000,6,False,False,True
10,Mercedez Benz C class,83000,20000,7,False,False,True
11,Mercedez Benz C class,79000,21000,7,False,False,True
12,Mercedez Benz C class,59000,33000,5,False,False,True

In [132]:
final = dum_cars.drop(['Car_Model', 'Mercedez Benz C class'], axis='columns')
final

    Milage  Sell_Price  Age  Audi A5  BMW X5
0    69000       18000    6    False    True
1    35000       34000    3    False    True
2    57000       26100    5    False    True
3    22500       40000    2    False    True
4    46000       31500    4    False    True
5    59000       29400    5     True   False
6    52000       32000    5     True   False
7    72000       19300    6     True   False
8    91000       12000    8     True   False
9    67000       22000    6    False   False
10   83000       20000    7    False   False
11   79000       21000    7    False   False
12   59000       33000    5    False   False

In [133]:
dum_cars.rename(columns={'Mercedez Benz C class':'Mercedez_C_class'}, inplace=True)

In [134]:
dum_cars

,Car_Model,Milage,Sell_Price,Age,Audi A5,BMW X5,Mercedez_C_class
0,BMW X5,69000,18000,6,False,True,False
1,BMW X5,35000,34000,3,False,True,False
2,BMW X5,57000,26100,5,False,True,False
3,BMW X5,22500,40000,2,False,True,False
4,BMW X5,46000,31500,4,False,True,False
5,Audi A5,59000,29400,5,True,False,False
6,Audi A5,52000,32000,5,True,False,False
7,Audi A5,72000,19300,6,True,False,False
8,Audi A5,91000,12000,8,True,False,False
9,Mercedez Benz C class,67000,22000,6,False,False,True
10,Mercedez Benz C class,83000,20000,7,False,False,True
11,Mercedez Benz C class,79000,21000,7,False,False,True
12,Mercedez Benz C class,59000,33000,5,False,False,True

In [113]:
dum_cars = dum_cars.drop('Car_Model', axis='columns')

In [114]:
dum_cars

    Milage  Sell_Price  Age  Audi A5  BMW X5  Mercedez_C_class
0    69000       18000    6    False    True             False
1    35000       34000    3    False    True             False
2    57000       26100    5    False    True             False
3    22500       40000    2    False    True             False
4    46000       31500    4    False    True             False
5    59000       29400    5     True   False             False
6    52000       32000    5     True   False             False
7    72000       19300    6     True   False             False
8    91000       12000    8     True   False             False
9    67000       22000    6    False   False              True
10   83000       20000    7    False   False              True
11   79000       21000    7    False   False              True
12   59000       33000    5    False   False              True

In [115]:
l_model = linear_model.LinearRegression()

In [135]:
y = final.Sell_Price
print(y)
X = final.drop('Sell_Price', axis = 'columns')
X

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell_Price, dtype: int64

    Milage  Age  Audi A5  BMW X5
0    69000    6    False    True
1    35000    3    False    True
2    57000    5    False    True
3    22500    2    False    True
4    46000    4    False    True
5    59000    5     True   False
6    52000    5     True   False
7    72000    6     True   False
8    91000    8     True   False
9    67000    6    False   False
10   83000    7    False   False
11   79000    7    False   False
12   59000    5    False   False

In [136]:
# l_model.fit(dum_cars[['Milage', 'Age', 'Audi A5', 'BMW X5', 'Mercedez_C_class']], cars.Sell_Price)
l_model.fit(X,y)

LinearRegression()

In [137]:
l_model.coef_

array([-3.70122094e-01, -1.33245363e+03, -2.45354074e+03, -6.73820733e+03])

In [138]:
l_model.intercept_

np.float64(58976.62596853723)

In [139]:
l_model.predict([[45000,4,0,0]])

C:\Users\hi\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([36991.31721061])

In [140]:
l_model.predict([[86000,7,1,0]])

C:\Users\hi\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([15365.40972059])