# <font color="purple"><h3 align="center">DataFrame Basics Tutorial</h3></font>

## **Dataframe is most commonly used object in `pandas`. It is a table like datastructure containing rows and columns similar to excel spreadsheet**

In [2]:
import pandas as pd
weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}
df = pd.DataFrame(weather_data)
df = pd.read_csv("weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [3]:
df.shape

(6, 4)

## Rows

In [4]:
df.head()

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [6]:
df.tail()

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [24]:
df[1:3]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

## Columns

In [25]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [28]:
df.day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          6 non-null      object
 1   temperature  6 non-null      int64
 2   windspeed    6 non-null      int64
 3   event        6 non-null      object
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [31]:
df[['day','temperature']]

        day  temperature
0  1/1/2017           32
1  1/2/2017           35
2  1/3/2017           28
3  1/4/2017           24
4  1/5/2017           32
5  1/6/2017           31

## Operations on DataFrame

In [32]:
df['temperature'].max()

35

In [37]:
df[df['temperature']>32]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [39]:
df['day'][df['temperature']==df['temperature'].max()]

1    1/2/2017
Name: day, dtype: object

In [41]:
df['day'][df['temperature'] == df['temperature'].min()]

3    1/4/2017
Name: day, dtype: object

In [51]:
df[df['temperature'] == df['temperature'].max()]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [54]:
df['temperature'].std()

3.8297084310253524

In [60]:
df['event'].max()

'Sunny'

In [58]:
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [150]:
import pandas as pd
w_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017', '1/6/2017'],
    'temperature': [32,35,28,32,31,33],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow', 'Rain', 'Sunny']
}
df = pd.DataFrame(w_data)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           32          7   Snow
4  1/5/2017           31          4   Rain
5  1/6/2017           33          2  Sunny

In [151]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           32          7   Snow
4  1/5/2017           31          4   Rain
5  1/6/2017           33          2  Sunny

In [152]:
df['event'].max()

'Sunny'

In [153]:
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     31.833333   4.666667
std       2.316607   2.338090
min      28.000000   2.000000
25%      31.250000   2.500000
50%      32.000000   5.000000
75%      32.750000   6.750000
max      35.000000   7.000000

**Google pandas series operations to find out list of all operations**
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.html

## <font color='blue'>set_index</font>

In [154]:
df.set_index('day')

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           32          7   Snow
1/5/2017           31          4   Rain
1/6/2017           33          2  Sunny

In [155]:
df.set_index('day', inplace=True)

In [156]:
df.index

Index(['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017'], dtype='object', name='day')

In [157]:
df.loc['1/2/2017']

temperature       35
windspeed          7
event          Sunny
Name: 1/2/2017, dtype: object

In [158]:
df.reset_index(inplace=True)

In [159]:
df.head()

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           32          7   Snow
4  1/5/2017           31          4   Rain

In [160]:
df.set_index('event',inplace=True) # this is kind of building a hash map using event as a key
df

            day  temperature  windspeed
event
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           32          7
Rain   1/5/2017           31          4
Sunny  1/6/2017           33          2

In [163]:
df.loc['Rain']

            day  temperature  windspeed
event
Rain   1/1/2017           32          6
Rain   1/5/2017           31          4

In [164]:
df.loc['Snow']

            day  temperature  windspeed
event
Snow   1/3/2017           28          2
Snow   1/4/2017           32          7

# <font color="purple"><h3 align="center">Pandas Concatenate Tutorial</h3></font>

## <font color='blue'>Basic Concatenation</font>

In [165]:
import pandas as pd

pakistani_weather = pd.DataFrame({
    "city": ["karachi","lahore","peshawar"],
    "temperature": [32,45,30],
    "humidity": [80, 60, 78]
})
pakistani_weather

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78

In [166]:
us_weather = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68, 65, 75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [170]:
# concat us and pakistani_weather

df = pd.concat([pakistani_weather, us_weather], ignore_index=True)
df

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78
3  new york           21        68
4   chicago           14        65
5   orlando           35        75

## <font color='blue'>Concatenation And Keys</font>

In [171]:
df = pd.concat([pakistani_weather, us_weather], keys=["pakistan", "us"])
df

                city  temperature  humidity
pakistan 0   karachi           32        80
         1    lahore           45        60
         2  peshawar           30        78
us       0  new york           21        68
         1   chicago           14        65
         2   orlando           35        75

In [183]:
# Show cities temperature, humidity of US cities
df.loc['us']

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [185]:
# Show cities temperature, humidity of Pakistani cities
df.loc['pakistan']

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78

## <font color='blue'>Concatenation Using Index</font>

In [186]:
temperature_df = pd.DataFrame({
    "city": ["karachi","lahore","peshawar"],
    "temperature": [32,45,30],
}, index=[0,1,2])
temperature_df

       city  temperature
0   karachi           32
1    lahore           45
2  peshawar           30

In [187]:
windspeed_df = pd.DataFrame({
    "city": ["lahore","karachi"],
    "windspeed": [7,12],
}, index=[1,0])
windspeed_df

      city  windspeed
1   lahore          7
0  karachi         12

In [198]:
#concatenate the temperature and windspeed of Lahore, Karachi and Peshawar

pd.merge(temperature_df, windspeed_df, how='left')

       city  temperature  windspeed
0   karachi           32       12.0
1    lahore           45        7.0
2  peshawar           30        NaN

## <font color='blue'>Concatenate dataframe with series</font>

In [199]:
s = pd.Series(['Humid', 'Dry', 'Rain'], name='event')
s

0    Humid
1      Dry
2     Rain
Name: event, dtype: object

In [202]:
df = pd.concat([temperature_df, s], axis=1)

In [203]:
df

       city  temperature  event
0   karachi           32  Humid
1    lahore           45    Dry
2  peshawar           30   Rain

## <font color="maroon"><h4 align="center">Pandas Group By</font>

In [204]:
import pandas as pd

In [206]:
df = pd.read_csv('weather_by_cities.csv')

In [207]:
df

         day      city  temperature  windspeed   event
0   1/1/2024  new york           32          6    Rain
1   1/2/2024  new york           36          7   Sunny
2   1/3/2024  new york           28         12    Snow
3   1/4/2024  new york           33          7   Sunny
4   1/1/2024     dubai           90          5   Sunny
5   1/2/2024     dubai           85         12     Fog
6   1/3/2024     dubai           87         15     Fog
7   1/4/2024     dubai           92          5    Rain
8   1/1/2024     paris           45         20   Sunny
9   1/2/2024     paris           50         13  Cloudy
10  1/3/2024     paris           54          8  Cloudy
11  1/4/2024     paris           42         10  Cloudy

### For this dataset, get following answers,
#### 1. What was the maximum temperature in each of these 3 cities?
#### 2. What was the average windspeed in each of these 3 cities?

In [209]:
df.groupby('city')['temperature'].max()

city
dubai       92
new york    36
paris       54
Name: temperature, dtype: int64

In [210]:
df.groupby('city')['windspeed'].mean()

city
dubai        9.25
new york     8.00
paris       12.75
Name: windspeed, dtype: float64

In [213]:
g = df.groupby('city')
g

In [217]:
for city, data in g : 
    print('\ncity', city)
    # print('\n')
    print('data', data)

city dubai
data         day   city  temperature  windspeed  event
4  1/1/2024  dubai           90          5  Sunny
5  1/2/2024  dubai           85         12    Fog
6  1/3/2024  dubai           87         15    Fog
7  1/4/2024  dubai           92          5   Rain

city new york
data         day      city  temperature  windspeed  event
0  1/1/2024  new york           32          6   Rain
1  1/2/2024  new york           36          7  Sunny
2  1/3/2024  new york           28         12   Snow
3  1/4/2024  new york           33          7  Sunny

city paris
data          day   city  temperature  windspeed   event
8   1/1/2024  paris           45         20   Sunny
9   1/2/2024  paris           50         13  Cloudy
10  1/3/2024  paris           54          8  Cloudy
11  1/4/2024  paris           42         10  Cloudy

In [218]:
g.get_group('paris')

         day   city  temperature  windspeed   event
8   1/1/2024  paris           45         20   Sunny
9   1/2/2024  paris           50         13  Cloudy
10  1/3/2024  paris           54          8  Cloudy
11  1/4/2024  paris           42         10  Cloudy

In [219]:
g.min()

               day  temperature  windspeed   event
city
dubai     1/1/2024           85          5     Fog
new york  1/1/2024           28          6    Rain
paris     1/1/2024           42          8  Cloudy

In [221]:
g.mean(numeric_only=True)

          temperature  windspeed
city
dubai           88.50       9.25
new york        32.25       8.00
paris           47.75      12.75

**This method of splitting your dataset in smaller groups and then applying an operation
(such as min or max) to get aggregate result is called Split-Apply-Combine.**

In [222]:
g.min()

               day  temperature  windspeed   event
city
dubai     1/1/2024           85          5     Fog
new york  1/1/2024           28          6    Rain
paris     1/1/2024           42          8  Cloudy

In [226]:
g.describe()

         temperature                                                   \
               count   mean       std   min    25%   50%    75%   max
city
dubai            4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0
new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0
paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0

         windspeed
             count   mean       std  min   25%   50%    75%   max
city
dubai          4.0   9.25  5.057997  5.0  5.00   8.5  12.75  15.0
new york       4.0   8.00  2.708013  6.0  6.75   7.0   8.25  12.0
paris          4.0  12.75  5.251984  8.0  9.50  11.5  14.75  20.0

In [227]:
g.size()

city
dubai       4
new york    4
paris       4
dtype: int64

# <font color="purple"><h3 align="center">Pandas Merge Tutorial</h3></font>

In [228]:
import pandas as pd
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
})
df1

       city  temperature
0  new york           21
1   chicago           14
2   orlando           35

In [229]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","orlando"],
    "humidity": [65,68,75],
})
df2

       city  humidity
0   chicago        65
1  new york        68
2   orlando        75

In [235]:
pd.merge(df1,df2)

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

## <font color='blue'>Type Of DataBase Joins</font>

In [236]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando", "baltimore"],
    "temperature": [21,14,35, 38],
})
df1

        city  temperature
0   new york           21
1    chicago           14
2    orlando           35
3  baltimore           38

In [237]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","san diego"],
    "humidity": [65,68,71],
})
df2

        city  humidity
0    chicago        65
1   new york        68
2  san diego        71

In [242]:
df3 = pd.merge(df1,df2,on='city', how='inner')
df3

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65

In [243]:
df3 = pd.merge(df1,df2,on='city', how='outer')
df3

        city  temperature  humidity
0  baltimore         38.0       NaN
1    chicago         14.0      65.0
2   new york         21.0      68.0
3    orlando         35.0       NaN
4  san diego          NaN      71.0

In [244]:
df3 = pd.merge(df1,df2,on='city', how='left')
df3

        city  temperature  humidity
0   new york           21      68.0
1    chicago           14      65.0
2    orlando           35       NaN
3  baltimore           38       NaN

In [245]:
df3 = pd.merge(df1,df2,on='city', how='right')
df3

        city  temperature  humidity
0    chicago         14.0        65
1   new york         21.0        68
2  san diego          NaN        71

## <font color='blue'>indicator flag</font>

In [247]:
df3 = pd.merge(df1,df2,on='city', how='outer',indicator=True)
df3

        city  temperature  humidity      _merge
0  baltimore         38.0       NaN   left_only
1    chicago         14.0      65.0        both
2   new york         21.0      68.0        both
3    orlando         35.0       NaN   left_only
4  san diego          NaN      71.0  right_only

## <font color='blue'>suffixes</font>

In [248]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando", "baltimore"],
    "temperature": [21,14,35,38],
    "humidity": [65,68,71, 75]
})
df1

        city  temperature  humidity
0   new york           21        65
1    chicago           14        68
2    orlando           35        71
3  baltimore           38        75

In [249]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","san diego"],
    "temperature": [21,14,35],
    "humidity": [65,68,71]
})
df2

        city  temperature  humidity
0    chicago           21        65
1   new york           14        68
2  san diego           35        71

In [250]:
df3= pd.merge(df1,df2,on="city",how="outer", suffixes=('_first','_second'))
df3

,city,temperature_first,humidity_first,temperature_second,humidity_second
0,baltimore,38.0,75.0,NaN,NaN
1,chicago,14.0,68.0,21.0,65.0
2,new york,21.0,65.0,14.0,68.0
3,orlando,35.0,71.0,NaN,NaN
4,san diego,NaN,NaN,35.0,71.0

## <font color='blue'>join</font>

In [252]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
})
df1.set_index('city',inplace=True)
df1

          temperature
city
new york           21
chicago            14
orlando            35

In [253]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","orlando"],
    "humidity": [65,68,75],
})
df2.set_index('city',inplace=True)
df2

          humidity
city
chicago         65
new york        68
orlando         75

In [255]:
import pandas as pd
import numpy as np
df = pd.read_csv("weather.csv")
df

       date      city  temperature  humidity
0  5/1/2024  new york           65        56
1  5/2/2024  new york           66        58
2  5/3/2024  new york           68        60
3  5/1/2024     dubai           75        80
4  5/2/2024     dubai           78        83
5  5/3/2024     dubai           82        85
6  5/1/2024   beijing           80        26
7  5/2/2024   beijing           77        30
8  5/3/2024   beijing           79        35

In [257]:
df.pivot(index='city', columns='date')

         temperature                   humidity
date        5/1/2024 5/2/2024 5/3/2024 5/1/2024 5/2/2024 5/3/2024
city
beijing           80       77       79       26       30       35
dubai             75       78       82       80       83       85
new york          65       66       68       56       58       60

In [258]:
df.pivot(index='city', columns='date', values='humidity')

date      5/1/2024  5/2/2024  5/3/2024
city
beijing         26        30        35
dubai           80        83        85
new york        56        58        60

In [259]:
df.pivot(index='date', columns='city')

         temperature                humidity
city         beijing dubai new york  beijing dubai new york
date
5/1/2024          80    75       65       26    80       56
5/2/2024          77    78       66       30    83       58
5/3/2024          79    82       68       35    85       60

In [260]:
df.pivot(index='city', columns='date',values='humidity')

date      5/1/2024  5/2/2024  5/3/2024
city
beijing         26        30        35
dubai           80        83        85
new york        56        58        60

In [261]:
import pandas as pd
import numpy as np
df = pd.read_csv("weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny